### ISSUE TITLE
ascmhl.readthedocs.io didn't update with master branch

### ISSUE THREAD

**Issue by ptrpfn** [ascmitc/mhl#103]
* The README at https://ascmhl.readthedocs.io/en/latest/README.html didn't update to latest changes in the master branch. 
* Also the "doc" tag on the top of the github page at https://github.com/ascmitc/mhl/blob/master/README.md has a "failed" status.

**Comment by jwaggs** [comment]
```
Running Sphinx v3.1.2
loading translations [en]... done
WARNING: while setting up extension sphinx.addnodes: node class 'meta' is already registered, its visitors will be overridden
making output directory... done
WARNING: html_static_path entry '_static' does not exist
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: [new config] 3 added, 0 changed, 0 removed
reading sources... [ 33%] README
reading sources... [ 66%] commands
reading sources... [100%] index

/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/checkouts/latest/docs/source/commands.rst:4: WARNING: Module "ascmhl" has no attribute "mhltool_cli"
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 33%] README

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 535, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 545, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 596, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/sphinx/writers/html.py", line 71, in translate
    self.document.walkabout(visitor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/docutils/nodes.py", line 199, in walkabout
    if child.walkabout(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/docutils/nodes.py", line 199, in walkabout
    if child.walkabout(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/docutils/nodes.py", line 191, in walkabout
    visitor.dispatch_visit(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/sphinx/util/docutils.py", line 468, in dispatch_visit
    method(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/sphinx/writers/html5.py", line 357, in visit_title
    super().visit_title(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/docutils/writers/_html_base.py", line 1661, in visit_title
    start_tag, close_tag = self.section_title_tags(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/docutils/writers/html5_polyglot/__init__.py", line 445, in section_title_tags
    if (ids and self.settings.section_self_link
AttributeError: 'Values' object has no attribute 'section_self_link'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascmhl/envs/latest/lib/python3.7/site-packages/docutils/writers/html5_polyglot/__init__.py", line 445, in section_title_tags
    if (ids and self.settings.section_self_link
AttributeError: 'Values' object has no attribute 'section_self_link'
The full traceback has been saved in /tmp/sphinx-err-hmq9_6id.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

This is the stacktrace on read the docs. Any idea what that might have caused that from your most recent merge @ptrpfn ?

**Comment by jwaggs** [comment]
It sure doesn't look like you changed much of anything other than the Readme in #102 - I'm working on the directory checksum issue today so I can take a look at this in a bit if you don't have any ideas @ptrpfn
