### ISSUE TITLE
Issues with nested histories

### ISSUE THREAD

**Issue by jwaggs** [ascmitc/mhl#46]
There seem to be a few different bugs with nested histories. Parent ignore spec updates override their child history ignore specs. Also, it was reported by Eric Hansen on slack that you can not update the checksum format in child histories. These should be investigated and addressed.

**Comment by ptrpfn** [comment]
https://docs.google.com/document/d/10UTRwTO6xEO-nexBBMMsHWcRCsvddVp9gs_uplo6bY4

**Comment by jwaggs** [comment]
The ignore functionality on nested histories no longer overrides the child history ignore spec but rather appends the new ignore patterns (if any) to the existing ignore patterns from the latest generation as of PR #40

**Comment by jwaggs** [comment]
There is a bug that causes a crash if a child mhl directory is deleted, then the parent mhl history operated upon. Running the create command on an existing history with a deleted child mhl directory results in the following stacktrace:

```
Traceback (most recent call last):
  File "/Users/jon/code/ascmhl/mhl/./ascmhl.py", line 37, in <module>
    mhltool_cli()
  File "/Users/jon/code/ascmhl/mhl/env/lib/python3.9/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jon/code/ascmhl/mhl/env/lib/python3.9/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/jon/code/ascmhl/mhl/env/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jon/code/ascmhl/mhl/env/lib/python3.9/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jon/code/ascmhl/mhl/env/lib/python3.9/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jon/code/ascmhl/mhl/mhl/commands.py", line 55, in create
    create_for_folder_subcommand(root_path, verbose, hash_format, no_directory_hashes, single_file)
  File "/Users/jon/code/ascmhl/mhl/mhl/commands.py", line 77, in create_for_folder_subcommand
    existing_history = MHLHistory.load_from_path(root_path)
  File "/Users/jon/code/ascmhl/mhl/mhl/history.py", line 222, in load_from_path
    history._find_and_load_child_histories()
  File "/Users/jon/code/ascmhl/mhl/mhl/history.py", line 240, in _find_and_load_child_histories
    self._resolve_hash_list_references()
  File "/Users/jon/code/ascmhl/mhl/mhl/history.py", line 265, in _resolve_hash_list_references
    history = self.child_history_mappings[reference_path]
```

We need to gracefully handle this error.

**Comment by ptrpfn** [comment]
Closing issue because is either solved or only an issue on very early versions.
