### ISSUE TITLE
Questions about the `--version` option

### ISSUE THREAD

**Issue by ptrpfn** [ascmitc/mhl#69]
The version command only works when the `ascmhl` command is installed via pip (pip3). 

From the command line it looks like this:

```
% ./mhl/cli/ascmhl.py --version                   
Traceback (most recent call last):
  File "./mhl/cli/ascmhl.py", line 38, in <module>
    mhltool_cli()
  File "/path/to/mhl/env/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/path/to/mhl/env/lib/python3.8/site-packages/click/core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/path/to/mhl/env/lib/python3.8/site-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/path/to/mhl/env/lib/python3.8/site-packages/click/core.py", line 1089, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/path/to/mhl/env/lib/python3.8/site-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/path/to/mhl/env/lib/python3.8/site-packages/click/core.py", line 1476, in handle_parse_result
    value = invoke_param_callback(
  File "/path/to/mhl/env/lib/python3.8/site-packages/click/core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "/path/to/mhl/env/lib/python3.8/site-packages/click/decorators.py", line 270, in callback
    raise RuntimeError('Could not determine version')
RuntimeError: Could not determine version
```

Is this intended?

**Comment by ptrpfn** [comment]
@cbenhagen Can you take a look? You know probably most about the changes for pip install. I also opened a pull request for a bit more info in the README on how to run `ascmhl.py` from the repository ( https://github.com/ascmitc/mhl/pull/68 ) after the "pip changes". Maybe you have an opinion on that, too. Thank you!

**Comment by cbenhagen** [comment]
This is expected behaviour, as when running the uninstalled script there is no way to determine the version. What would be the use case for running `./mhl/cli/ascmhl.py` instead of the installed (and maybe editable) `ascmhl` from your `$PATH`?

**Comment by ptrpfn** [comment]
Running `./mhl/cli/ascmhl.py` simply was _the_ way to use the repository for testing new features as part of the group discussions so far (including switching between branches, testing different behavior etc.). Not everyone is a developer in the group and uses an IDE). This may not have advantages beyond that it worked, but it should be documented how to use it now (see discussion in pull request #68 ).

**Comment by cbenhagen** [comment]
Ok, I see. Sorry for the breaking change then! I will add more information to the `README` on how to install, run and update using pip for developers and users.

**Comment by ptrpfn** [comment]
Ok great, that sounds good. Thank you, Ben!

**Comment by ptrpfn** [comment]
Jon brought another question about that version, but unfortunately we could not discuss that in the last meeting. I'll change the title to a more general topic about "the version" and invite @jwaggs to add his findings here. Maybe we leave it open then for now.

**Comment by jwaggs** [comment]
sorry for the delay this is good to go.
